export function buildRemotePage(): string {
  return `<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#0b1420">
  <title>ICP Studio Remote</title>
  <style>
    :root{color-scheme:dark;--bg:#080e16;--surface:#101a27;--line:#26384e;--muted:#8492a6;--text:#e8eef6;--primary:#60a5fa;--success:#35d07f;--danger:#ef6464;--active-content-background:#153250;--active-content-border:#427bb4;--active-content-text:#dbeafe;--inactive-content-text:#8fa0b5;--active-content-font-size:10px;--active-content-lines:2}
    *{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{height:100%}body{margin:0;overflow:hidden;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button{color:inherit}
    .app{display:flex;height:100dvh;flex-direction:column;background:radial-gradient(circle at 50% -20%,#173252 0,#0b1420 35%,#080e16 72%)}
    .topbar{display:flex;align-items:center;gap:10px;padding:calc(9px + env(safe-area-inset-top)) 12px 9px;background:rgba(10,18,28,.96);border-bottom:1px solid #213044;backdrop-filter:blur(16px)}
    .icon-button{display:grid;width:39px;height:39px;flex:0 0 39px;padding:0;place-items:center;background:#111e2d;border:1px solid #2a3d55;border-radius:10px;cursor:pointer}.brand{min-width:0;flex:1}.brand strong{display:block;font-size:15px}.brand small{display:flex;align-items:center;gap:6px;color:#8fa0b5;font-size:9px}.status-dot{width:7px;height:7px;background:var(--success);border-radius:50%;box-shadow:0 0 0 3px rgba(53,208,127,.12)}
    .area-bar{display:flex;align-items:center;gap:8px;padding:8px 12px;background:#0c1520;border-bottom:1px solid #1f2e40}.area-label{display:flex;align-items:center;gap:5px;color:#7290aa;font-size:8px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.area-select-wrap{position:relative;min-width:0;flex:1}.area-select{width:100%;height:36px;padding:0 34px 0 12px;color:#e2edf8;background:linear-gradient(180deg,#122233,#0d1926);border:1px solid #304a63;border-radius:9px;outline:none;font-size:11px;font-weight:700;appearance:none}.area-select-wrap::after{position:absolute;top:50%;right:12px;color:#7390aa;content:'⌄';transform:translateY(-55%);pointer-events:none}.area-live-dot{width:7px;height:7px;background:#4ade80;border-radius:50%}
    .tabs{display:grid;grid-template-columns:1fr 1fr;padding:6px 12px 0;background:#0c1520;border-bottom:1px solid #1f2e40}.tab{position:relative;min-height:43px;color:#7f8da0;background:transparent;border:0}.tab.active{color:#bfdbfe}.tab.active::after{position:absolute;right:15%;bottom:0;left:15%;height:3px;background:var(--primary);border-radius:3px 3px 0 0;content:''}.tab-badge{margin-left:5px;padding:2px 5px;background:#24374d;border-radius:9px;font-size:9px}
    .content{min-height:0;flex:1;overflow:auto}.screen{display:none;width:min(100%,1050px);min-height:100%;margin:0 auto;padding:12px 12px calc(22px + env(safe-area-inset-bottom))}.screen.active{display:block}.section-label{display:flex;justify-content:space-between;margin:3px 2px 8px;color:#8192a7;font-size:9px;text-transform:uppercase;letter-spacing:.07em}.section-label span:last-child{color:#61748b;text-transform:none;letter-spacing:0}
    .layout{display:grid;gap:11px}.card{overflow:hidden;background:#0e1926;border:1px solid var(--line);border-radius:13px;box-shadow:0 16px 36px rgba(0,0,0,.2)}.card-head{display:flex;min-height:38px;align-items:center;justify-content:space-between;padding:0 11px;color:#8797aa;background:#132031;border-bottom:1px solid #273a50;font-size:9px}.card-head b{color:#b9c7d7}.projection{position:relative;display:flex;aspect-ratio:16/9;align-items:center;justify-content:center;padding:18px;overflow:hidden;background:radial-gradient(circle at center,#173b67,#05080d 68%);text-align:center}.preview-surface{display:flex;width:100%;height:100%;align-items:center;justify-content:center;overflow:hidden}.preview-surface img,.preview-surface video{width:100%;height:100%;object-fit:contain}.preview-copy{display:flex;width:100%;height:100%;align-items:center;justify-content:center;overflow:hidden;color:#f2f7fd;font-size:clamp(13px,4vw,28px);font-weight:650;line-height:1.25;text-align:center;white-space:pre-line}.placeholder{display:flex;align-items:center;flex-direction:column;gap:8px;color:#6f8095;font-size:11px}.placeholder span{font-size:38px}.footer{position:absolute;right:10px;bottom:8px;left:10px;color:#9fb4ca;font-size:8px}
    .details{padding:11px}.details-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.details-head div{min-width:0}.details-head small{display:block;color:var(--muted);font-size:9px}.details-head strong{display:block;overflow:hidden;margin-top:2px;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.count{padding:4px 7px;color:#9ecbfa;background:#173252;border-radius:9px;font-size:9px}.parts,.service-list{display:grid;gap:5px;max-height:245px;overflow:auto}.part,.service-item{width:100%;padding:8px 9px;color:var(--inactive-content-text);background:#0c1622;border:1px solid #26394f;border-radius:8px;text-align:left}.part.active{color:var(--active-content-text);background:var(--active-content-background);border-color:var(--active-content-border)}.part b,.service-item b{display:block;overflow:hidden;font-size:var(--active-content-font-size);text-overflow:ellipsis}.part small,.service-item small{display:block;margin-top:3px;color:#73859a;font-size:8px}.part-preview{display:-webkit-box;margin-top:4px;overflow:hidden;line-height:1.35;-webkit-box-orient:vertical;-webkit-line-clamp:var(--active-content-lines)}
    .controls{display:grid;grid-template-columns:42px minmax(0,1fr) 42px;gap:6px;margin-top:9px}.control{min-height:40px;background:#111e2d;border:1px solid #2c415a;border-radius:9px}.control.primary{color:#eaf4ff;background:#1769aa;border-color:#3187cb;font-size:10px;font-weight:650}.control:disabled{opacity:.35}.live-indicator{display:flex;align-items:center;gap:7px;color:#fca5a5}.live-dot{width:7px;height:7px;background:var(--danger);border-radius:50%;box-shadow:0 0 0 4px rgba(239,100,100,.12)}
    .service-panel{margin-top:11px;padding:11px;background:var(--surface);border:1px solid var(--line);border-radius:13px}.service-panel-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.service-panel-head strong{font-size:12px}.service-panel-head span{color:#7e91a6;font-size:9px}
    .backdrop{position:fixed;z-index:20;inset:0;background:rgba(2,6,11,.72);opacity:0;pointer-events:none;transition:.2s;backdrop-filter:blur(3px)}.backdrop.open{opacity:1;pointer-events:auto}.drawer{position:fixed;z-index:30;top:0;bottom:0;left:0;width:min(86vw,330px);padding:calc(18px + env(safe-area-inset-top)) 12px 16px;overflow:auto;background:#0d1723;border-right:1px solid #2b3e54;transform:translateX(-105%);transition:.23s}.drawer.open{transform:translateX(0)}.drawer-head{display:flex;align-items:center;gap:10px;padding:0 4px 16px}.drawer-logo{display:grid;width:42px;height:42px;place-items:center;color:#8fc7ff;background:#173252;border:1px solid #315a84;border-radius:11px}.drawer-head div{min-width:0;flex:1}.drawer-head strong,.drawer-head small{display:block}.drawer-head small{color:var(--muted);font-size:9px}.drawer-section{margin:12px 8px 7px;color:#60738a;font-size:8px;text-transform:uppercase}.module-button{display:grid;width:100%;min-height:47px;grid-template-columns:37px minmax(0,1fr) 18px;align-items:center;gap:6px;margin-bottom:4px;padding:4px 8px;color:#9baabd;background:transparent;border:0;border-radius:9px;text-align:left}.module-icon{display:grid;width:33px;height:33px;place-items:center;color:#8bbef2;background:#132338;border-radius:8px}.module-button b{font-size:11px}.module-button small{display:block;color:#62748a;font-size:8px}
    .explorer{position:fixed;z-index:40;inset:0;display:flex;flex-direction:column;background:#09111b;transform:translateY(105%);transition:.25s}.explorer.open{transform:translateY(0)}.explorer-head{display:flex;align-items:center;gap:9px;padding:calc(9px + env(safe-area-inset-top)) 12px 9px;background:#0d1825;border-bottom:1px solid #28394e}.explorer-head div{min-width:0;flex:1}.explorer-head strong,.explorer-head small{display:block}.explorer-head small{color:var(--muted);font-size:8px}.explorer-body{min-height:0;flex:1;padding:13px;overflow:auto}.search{display:flex;gap:7px}.search input{min-width:0;height:42px;flex:1;padding:0 12px;color:#e8eef6;background:#101c2a;border:1px solid #344a64;border-radius:10px;outline:0}.search button{width:42px;color:#eaf4ff;background:#1769aa;border:0;border-radius:9px}.results{display:grid;gap:7px;margin-top:10px}.result{display:grid;grid-template-columns:48px minmax(0,1fr) auto;align-items:center;gap:8px;padding:8px;color:#b9c6d5;background:#0e1926;border:1px solid #283c53;border-radius:10px;text-align:left}.thumb{display:grid;width:48px;height:44px;place-items:center;overflow:hidden;color:#8fc2f4;background:#15283d;border-radius:7px}.thumb img,.thumb video{width:100%;height:100%;object-fit:cover}.result b,.result small{display:block;overflow:hidden;text-overflow:ellipsis}.result b{font-size:11px;white-space:nowrap}.result small{margin-top:3px;color:#74869c;font-size:8px}.result-actions{display:none;gap:6px;margin-top:10px}.result-actions.visible{display:flex}.result-actions button{flex:1;min-height:38px;color:#d8eaff;background:#153250;border:1px solid #315b82;border-radius:8px;font-size:9px}.message{padding:24px;color:#74869c;text-align:center}.hidden{display:none!important}
    @media(min-width:760px){.layout{grid-template-columns:minmax(0,1.35fr) minmax(300px,.75fr);align-items:start}.screen{padding:18px 22px 28px}.details{position:sticky;top:0}.explorer-body{width:min(100%,950px);margin:0 auto;padding:20px}}
  </style>
</head>
<body>
<div class="app">
  <header class="topbar">
    <button id="open-menu" class="icon-button" type="button">☰</button>
    <div class="brand"><strong>ICP Studio Remote</strong><small><i class="status-dot"></i><span id="status">Conectando…</span></small></div>
  </header>
  <div class="area-bar"><span class="area-label"><i class="area-live-dot"></i>Pantalla</span><span class="area-select-wrap"><select id="output-select" class="area-select"><option value="">Salida actual</option></select></span></div>
  <nav class="tabs"><button class="tab active" data-tab="preview">▣ Previsualización</button><button class="tab" data-tab="live">◉ En vivo <span id="live-badge" class="tab-badge">0</span></button></nav>
  <main class="content">
    <section id="preview-screen" class="screen active"><div class="layout">
      <div><div class="section-label"><span>Vista del operador</span><span id="preview-position">Sin contenido</span></div><article class="card"><div class="card-head"><b>Previsualización</b><span>Operador</span></div><div class="projection"><div id="preview-surface" class="preview-surface"><div class="placeholder"><span>▣</span><b>Selecciona contenido</b></div></div><span id="preview-footer" class="footer"></span></div></article></div>
      <article id="preview-details" class="card details hidden"><div class="details-head"><div><small>Contenido seleccionado</small><strong id="preview-title"></strong></div><span id="preview-count" class="count"></span></div><div id="preview-parts" class="parts"></div><div class="controls"><button id="preview-previous" class="control">‹</button><button id="send-preview-live" class="control primary">Enviar a en vivo</button><button id="preview-next" class="control">›</button></div></article>
    </div></section>
    <section id="live-screen" class="screen"><div class="layout">
      <div><div class="section-label"><span class="live-indicator"><i class="live-dot"></i><span id="live-area-label">Salida</span></span><span id="live-position">Sin contenido</span></div><article class="card"><div class="card-head"><b>En vivo</b><span id="live-status">Esperando contenido</span></div><div class="projection"><div id="live-surface" class="preview-surface"><div class="placeholder"><span>◉</span><b>Sin contenido en vivo</b></div></div><span id="live-footer" class="footer"></span></div></article><section class="service-panel"><div class="service-panel-head"><strong>Servicio de esta pantalla</strong><span id="service-count">0 elementos</span></div><div id="service-list" class="service-list"><div class="message">El servicio aparecerá aquí.</div></div></section></div>
      <article id="live-details" class="card details hidden"><div class="details-head"><div><small>Contenido activo</small><strong id="live-title"></strong></div><span id="live-count" class="count"></span></div><div id="live-parts" class="parts"></div><div class="controls"><button id="live-previous" class="control">‹</button><button id="live-media-control" class="control primary hidden">Reproducir</button><span id="live-navigation-label" class="control" style="display:grid;place-items:center;font-size:9px;color:#7e91a6">Selecciona contenido</span><button id="live-next" class="control">›</button></div></article>
    </div></section>
  </main>
</div>
<div id="backdrop" class="backdrop"></div>
<aside id="drawer" class="drawer"><div class="drawer-head"><div class="drawer-logo">▶</div><div><strong>ICP Studio</strong><small>Contenido remoto</small></div><button id="close-menu" class="icon-button">×</button></div><div class="drawer-section">Contenido</div>
  <button class="module-button" data-module="Alabanzas" data-icon="♫"><span class="module-icon">♫</span><span><b>Alabanzas</b><small>Letras y estrofas</small></span><span>›</span></button>
  <button class="module-button" data-module="Música" data-icon="♪"><span class="module-icon">♪</span><span><b>Música</b><small>Audios y pistas</small></span><span>›</span></button>
  <button class="module-button" data-module="Biblia" data-icon="▤"><span class="module-icon">▤</span><span><b>Biblia</b><small>Versículos</small></span><span>›</span></button>
  <button class="module-button" data-module="Imágenes" data-icon="▧"><span class="module-icon">▧</span><span><b>Imágenes</b><small>Biblioteca visual</small></span><span>›</span></button>
  <button class="module-button" data-module="Videos" data-icon="▷"><span class="module-icon">▷</span><span><b>Videos</b><small>Archivos de video</small></span><span>›</span></button>
  <button class="module-button" data-module="Documentos" data-icon="▱"><span class="module-icon">▱</span><span><b>Documentos</b><small>PDF y presentaciones</small></span><span>›</span></button>
</aside>
<section id="explorer" class="explorer"><header class="explorer-head"><button id="close-explorer" class="icon-button">‹</button><span id="explorer-icon" class="module-icon">▤</span><div><strong id="explorer-title">Biblia</strong><small>Buscar contenido</small></div></header><div class="explorer-body"><form id="search-form" class="search"><input id="module-search" type="search" placeholder="Buscar"><button>↵</button></form><div id="result-actions" class="result-actions"><button id="add-selection-service">Agregar al servicio</button><button id="preview-selection">Previsualizar</button><button id="project-selection">Proyectar</button></div><div id="results" class="results"><div class="message">Busca contenido de ICP Studio.</div></div></div></section>
<script>
const statusEl=document.getElementById('status'),outputSelect=document.getElementById('output-select');
const drawer=document.getElementById('drawer'),backdrop=document.getElementById('backdrop'),explorer=document.getElementById('explorer'),results=document.getElementById('results'),searchInput=document.getElementById('module-search'),resultActions=document.getElementById('result-actions');
const moduleKeys={Alabanzas:'song',Música:'audio',Biblia:'bible',Imágenes:'image',Videos:'video',Documentos:'document'};const symbols={song:'♫',audio:'♪',bible:'▤',image:'▧',video:'▷',document:'▱',activity:'✦',tool:'⌁'};
let currentState=null,selectedOutputId='',activeModule='bible',selectedResult=null,searchTimer=0;
function apiUrl(path,params){const url=new URL(path,location.origin);Object.entries(params||{}).forEach(([k,v])=>url.searchParams.set(k,String(v)));return url.toString()}
async function api(path,options,params){const response=await fetch(apiUrl(path,params),options);const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo completar la solicitud.');return data}
function selectedOutput(state=currentState){const list=state?.outputs||[];return list.find(o=>o.outputId===selectedOutputId)||list.find(o=>o.outputId===state?.activeOutputId)||list[0]||null}
function outputPayload(payload={}){return selectedOutputId?{...payload,outputId:selectedOutputId}:payload}
async function post(path,payload={}){const state=await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(outputPayload(payload))});updateState(state);return state}
function mediaUrl(path){return path?apiUrl(path):''}
function setDrawer(open){drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open)}
document.getElementById('open-menu').onclick=()=>setDrawer(true);document.getElementById('close-menu').onclick=()=>setDrawer(false);backdrop.onclick=()=>setDrawer(false);
function activateTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===name+'-screen'))}
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>activateTab(tab.dataset.tab));
function escapeText(value){const span=document.createElement('span');span.textContent=value||'';return span.innerHTML}
function renderSurface(id,item,isLive){const surface=document.getElementById(id);surface.innerHTML='';if(!item){surface.innerHTML='<div class="placeholder"><span>'+ (isLive?'◉':'▣') +'</span><b>Sin contenido</b></div>';return}const frame=item.frame;if(frame.mediaType==='image'){const img=document.createElement('img');img.src=mediaUrl(frame.mediaPath);surface.append(img)}else if(frame.mediaType==='video'){const video=document.createElement('video');video.src=mediaUrl(frame.mediaPath);video.muted=isLive;video.controls=!isLive;video.playsInline=true;surface.append(video)}else if(frame.mediaType==='audio'){const div=document.createElement('div');div.className='placeholder';div.innerHTML='<span>♪</span><b>'+escapeText(item.title)+'</b>';surface.append(div)}else if(frame.mediaType==='document'){const div=document.createElement('div');div.className='placeholder';div.innerHTML='<span>▱</span><b>'+escapeText(item.title)+'</b><small>'+escapeText(frame.label)+'</small>';surface.append(div)}else{const div=document.createElement('div');div.className='preview-copy';div.textContent=frame.text||frame.label;surface.append(div)}}
function renderParts(id,item,setter){const box=document.getElementById(id);box.innerHTML='';if(!item)return;item.frames.forEach((frame,index)=>{const b=document.createElement('button');b.className='part'+(index===item.frameIndex?' active':'');const label=document.createElement('b');label.textContent=frame.label||String(index+1);b.append(label);if(frame.text){const p=document.createElement('span');p.className='part-preview';p.textContent=frame.text;b.append(p)}b.onclick=()=>setter(index);box.append(b)});box.querySelector('.active')?.scrollIntoView({block:'nearest'})}
function renderPreview(preview){const details=document.getElementById('preview-details');if(!preview){details.classList.add('hidden');renderSurface('preview-surface',null,false);document.getElementById('preview-position').textContent='Sin contenido';return}details.classList.remove('hidden');document.getElementById('preview-title').textContent=preview.title;document.getElementById('preview-count').textContent=preview.frameCount+' partes';document.getElementById('preview-position').textContent=(preview.frameIndex+1)+' de '+preview.frameCount;document.getElementById('preview-footer').textContent=preview.footer||'';renderSurface('preview-surface',preview,false);renderParts('preview-parts',preview,i=>post('/api/preview/frame',{frameIndex:i}));document.getElementById('preview-previous').disabled=preview.frameIndex<=0;document.getElementById('preview-next').disabled=preview.frameIndex>=preview.frameCount-1}
function renderService(output){const list=document.getElementById('service-list');list.innerHTML='';document.getElementById('service-count').textContent=(output?.serviceCount||0)+' elementos';if(!output?.serviceItems?.length){list.innerHTML='<div class="message">No hay elementos en el servicio de esta pantalla.</div>';return}output.serviceItems.forEach((item,index)=>{const row=document.createElement('div');row.className='service-item';const title=document.createElement('b');title.textContent=(index+1)+'. '+item.title;const info=document.createElement('small');info.textContent=(symbols[item.module]||'◫')+' · '+item.frameCount+' partes';row.append(title,info);list.append(row)})}
function renderLive(output){const live=output?.live||null;document.getElementById('live-area-label').textContent=output?.name||'Salida';document.getElementById('live-badge').textContent=live?'1':'0';renderService(output);const details=document.getElementById('live-details');if(!live){details.classList.add('hidden');renderSurface('live-surface',null,true);document.getElementById('live-position').textContent='Sin contenido';document.getElementById('live-status').textContent='Esperando contenido';return}details.classList.remove('hidden');document.getElementById('live-title').textContent=live.title;document.getElementById('live-count').textContent=live.frameCount+' partes';document.getElementById('live-position').textContent=(live.frameIndex+1)+' de '+live.frameCount;document.getElementById('live-status').textContent='Proyectando en '+(output?.name||'salida');document.getElementById('live-footer').textContent=live.footer||'';renderSurface('live-surface',live,true);renderParts('live-parts',live,i=>post('/api/live/frame',{frameIndex:i}));document.getElementById('live-previous').disabled=live.frameIndex<=0;document.getElementById('live-next').disabled=live.frameIndex>=live.frameCount-1;const media=live.module==='audio'||live.module==='video';document.getElementById('live-media-control').classList.toggle('hidden',!media);document.getElementById('live-navigation-label').classList.toggle('hidden',media);document.getElementById('live-media-control').textContent=output?.mediaPlayback?.isPlaying?'Pausar':'Reproducir'}
function applySettings(state){const s=state?.activeContent;if(!s)return;const root=document.documentElement;root.style.setProperty('--active-content-background',s.activeBackgroundColor);root.style.setProperty('--active-content-border',s.activeBorderColor);root.style.setProperty('--active-content-text',s.activeTextColor);root.style.setProperty('--inactive-content-text',s.inactiveTextColor);root.style.setProperty('--active-content-font-size',s.fontSize+'px');root.style.setProperty('--active-content-lines',String(s.visibleLines))}
function syncOutputOptions(state){const list=state?.outputs||[];const previous=selectedOutputId;if(!previous||!list.some(o=>o.outputId===previous))selectedOutputId=state?.activeOutputId&&list.some(o=>o.outputId===state.activeOutputId)?state.activeOutputId:(list[0]?.outputId||'');outputSelect.innerHTML='';if(!list.length){const op=document.createElement('option');op.value='';op.textContent='Salida actual';outputSelect.append(op);return}list.forEach(o=>{const op=document.createElement('option');op.value=o.outputId;op.textContent=o.name+(o.isOperatorArea?' · operador':'');outputSelect.append(op)});outputSelect.value=selectedOutputId}
function updateState(state){if(!state)return;currentState=state;applySettings(state);syncOutputOptions(state);renderPreview(state.preview);renderLive(selectedOutput(state))}
outputSelect.onchange=()=>{selectedOutputId=outputSelect.value;renderLive(selectedOutput());api('/api/state').then(updateState).catch(()=>{})};
document.getElementById('preview-previous').onclick=()=>post('/api/preview/move',{direction:-1});document.getElementById('preview-next').onclick=()=>post('/api/preview/move',{direction:1});document.getElementById('send-preview-live').onclick=async()=>{await post('/api/live');activateTab('live')};document.getElementById('live-previous').onclick=()=>post('/api/live/move',{direction:-1});document.getElementById('live-next').onclick=()=>post('/api/live/move',{direction:1});document.getElementById('live-media-control').onclick=()=>{const output=selectedOutput();return post('/api/live/media',{action:output?.mediaPlayback?.isPlaying?'pause':'play'})};
function thumb(item){const box=document.createElement('span');box.className='thumb';if(item.mediaPath&&item.module==='image'){const i=document.createElement('img');i.src=mediaUrl(item.mediaPath);box.append(i)}else if(item.mediaPath&&item.module==='video'){const v=document.createElement('video');v.src=mediaUrl(item.mediaPath);v.muted=true;box.append(v)}else box.textContent=symbols[item.module]||'◫';return box}
function renderResults(data){results.innerHTML='';selectedResult=null;resultActions.classList.remove('visible');if(!data.items?.length){results.innerHTML='<div class="message">No encontramos resultados.</div>';return}data.items.forEach(item=>{const row=document.createElement('button');row.className='result';const copy=document.createElement('span');const title=document.createElement('b');title.textContent=item.title;const sub=document.createElement('small');sub.textContent=item.subtitle||item.badge;copy.append(title,sub);row.append(thumb(item),copy,document.createTextNode('›'));row.onclick=()=>{if(item.suggestionQuery){searchInput.value=item.suggestionQuery;loadCatalog();return}selectedResult=item;resultActions.classList.add('visible')};results.append(row)})}
async function loadCatalog(){results.innerHTML='<div class="message">Cargando…</div>';try{renderResults(await api('/api/catalog',undefined,{module:activeModule,query:searchInput.value.trim()}))}catch(e){results.innerHTML='<div class="message">'+escapeText(e.message)+'</div>'}}
function itemPayload(item){return outputPayload({module:item.module,itemId:item.id,groupReference:item.groupReference||'',frameIndex:item.frameIndex||0})}
document.querySelectorAll('.module-button').forEach(button=>button.onclick=()=>{activeModule=moduleKeys[button.dataset.module]||'document';document.getElementById('explorer-title').textContent=button.dataset.module;document.getElementById('explorer-icon').textContent=button.dataset.icon;searchInput.value='';setDrawer(false);explorer.classList.add('open');loadCatalog()});document.getElementById('close-explorer').onclick=()=>explorer.classList.remove('open');document.getElementById('search-form').onsubmit=e=>{e.preventDefault();loadCatalog()};searchInput.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadCatalog,220)};
document.getElementById('add-selection-service').onclick=async()=>{if(selectedResult)await post('/api/service',itemPayload(selectedResult))};document.getElementById('preview-selection').onclick=async()=>{if(!selectedResult)return;const state=await post('/api/preview',itemPayload(selectedResult));updateState(state);explorer.classList.remove('open');activateTab('preview')};document.getElementById('project-selection').onclick=async()=>{if(!selectedResult)return;const state=await post('/api/live/item',itemPayload(selectedResult));updateState(state);explorer.classList.remove('open');activateTab('live')};
const events=new EventSource('/events');events.onopen=()=>statusEl.textContent='Conectado';events.onerror=()=>statusEl.textContent='Reconectando…';events.addEventListener('state',event=>updateState(JSON.parse(event.data)));
api('/api/state').then(updateState).catch(()=>{});setInterval(()=>api('/api/state').then(updateState).catch(()=>{}),1200);
</script>
</body></html>`;
}
